### ISSUE TITLE
Add SMRPG support

### ISSUE THREAD

**Issue by Z-RAY-Z** [baferpro/Gangs#1]
I advice you add support for SMRPG mod https://github.com/peace-maker/smrpg
This is popular mod, you can add ability to buy RPG experience multiplier and RPG credits multiplier in Gangs.
If you want, i can rewrite this in Russian.

**Comment by WhyFaust** [comment]
@Z-RAY-Z What exactly do you want to see? Gang management (Buying and other) for rpg credits or some kind of gang module (e.g. rpg experience booster)?

**Comment by Z-RAY-Z** [comment]
> or some kind of gang module (e.g. rpg experience booster)?

Exactly this

**Comment by WhyFaust** [comment]
https://github.com/baferpro/Gangs/commit/83d08065ca878d4ff5ef07c7ae7bdec089d546d2 I did, but did not check, please check, and tell me if everything is good and works as it should or vice versa.
