### ISSUE TITLE
Errors with adminmenu, newest version, all clear

### ISSUE THREAD

**Issue by dzagu** [baferpro/Gangs#2]
L 04/24/2021 - 10:12:42: [SM] Blaming: gangs_health.smx
L 04/24/2021 - 10:12:42: [SM] Call stack trace:
L 04/24/2021 - 10:12:42: [SM]   [0] GameCMS_GetClientName
L 04/24/2021 - 10:12:42: [SM]   [1] Line 339, E:\BaFeR\SM_1_10_Private\gangs_health.sp::MenuHandler_MainMenu
L 04/24/2021 - 10:12:42: [gangs.smx] Error (0): Column count doesn't match value count at row 1
L 04/24/2021 - 10:13:17: [SM] Exception reported: Native is not bound
L 04/24/2021 - 10:13:17: [SM] Blaming: gangs.smx
L 04/24/2021 - 10:13:17: [SM] Call stack trace:
L 04/24/2021 - 10:13:17: [SM]   [0] Shop_GetClientCredits
L 04/24/2021 - 10:13:17: [SM]   [1] Line 1959, E:\BaFeR\SM_1_10_Private\gangs.sp::OpenAdministrationMenu
L 04/24/2021 - 10:13:17: [SM]   [2] Line 346, gangs/Menus.sp::GangsMenu_Callback

**Comment by dzagu** [comment]
Using myjs

**Comment by WhyFaust** [comment]
As I understand it, we have already resolved this issue. So if that's the case, then close the ticket.
