### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by dzagu** [baferpro/Gangs#3]
The same in translation
	"TransferLeader"
	{
		"en"		"Leadership Transfer"
		"ru"		"Передача лидерства"
	}

	"TransferLeader"
	{
		"en"		"Leadership Transfer"
		"ru"		"Передача лидерства"
	}

**Comment by WhyFaust** [comment]
fixed in https://github.com/baferpro/Gangs/commit/946b9cd29178c08d94fd6bfc2b1ebf0f4b25db7e
