### ISSUE TITLE
Array index out of bound

### ISSUE THREAD

**Issue by nuclearsilo583** [baferpro/Gangs#7]
[SM] Exception reported: Array index out-of-bounds (index -1, limit 256)
L 01/10/2022 - 10:19:28: [SM] Blaming: gangs\gangs.smx
L 01/10/2022 - 10:19:28: [SM] Call stack trace:
L 01/10/2022 - 10:19:28: [SM]   [1] Line 567, gangs/Helpers.sp::ResetVariables
L 01/10/2022 - 10:19:28: [SM]   [2] Line 145, gangs.sp::OnClientConnected

[SM] Exception reported: Array index out-of-bounds (index -1, limit 256)
L 01/10/2022 - 10:26:48: [SM] Blaming: gangs\gangs.smx
L 01/10/2022 - 10:26:48: [SM] Call stack trace:
L 01/10/2022 - 10:26:48: [SM]   [1] Line 521, gangs/Database.sp::SQLCallback_CheckName

This my error log how can I fix this

**Comment by WhyFaust** [comment]
https://github.com/baferpro/Gangs/commit/261594f0c666f55d69439a1506b76fa6ffcec511
