### ISSUE TITLE
Connect Gangs to MyJailShop

### ISSUE THREAD

**Issue by ppzinx** [baferpro/Gangs#8]
how do i set up plugin to work with  [CS:GO] MyJailShop [url]https://forums.alliedmods.net/showthread.php?t=288712[/url] credits???
i edited some gangs settings and settings.txt file but i don't konw what more i need to do, to connect plugin to MyJailShop credits.

and i have this error log, how to fix? or just what to fix, i know that i don't have all the plugins that could work with gangs.

I just want to know what i need to do, to get gangs plugin to work corectly and with MyJailShop.

error logs:
[url]https://ibb.co/KxkCssm[/url]
[url]https://ibb.co/fr5bt8c[/url]
[url]https://ibb.co/4dMtvsF[/url]
[url]https://ibb.co/LhCJz43[/url]

**Comment by WhyFaust** [comment]
Specify the payment method number 5 in the plug-in settings. If it doesn't work, then just the last number + 1. It should work. After that I will make a normal description. 

As for the errors, you need to connect the plugin to MySQL. And also disable modules that are not needed and are not used. For example, an RPG module that is not on your server.
